param(
    [Parameter(Mandatory=$true)]
    [string]$FeatureName
)

Write-Host "Creating HooshyarOS Feature: $FeatureName"


$enginePath = "Backend/HBOS/Engines/$FeatureName.ts"
$testPath = "Backend/HBOS/test/$FeatureName.test.ts"
$docPath = "Docs/$FeatureName.md"


$engineContent = @"
export class $FeatureName {

    initialize() {
        console.log("$FeatureName Started")
    }


    execute() {

        return {
            status: "READY"
        }

    }

}
"@


$testContent = @"
import { $FeatureName } from "../Engines/$FeatureName";


describe("$FeatureName",()=>{


test("should initialize feature",()=>{


const engine =
new $FeatureName();


expect(engine.execute().status)
.toBe("READY");


});


});
"@


$docContent = @"
# $FeatureName

## Purpose

New HooshyarOS capability.


## Status

Generated by AI Factory.


## Test

Automated Jest test included.
"@



New-Item -ItemType File -Force -Path $enginePath
Set-Content $enginePath $engineContent


New-Item -ItemType File -Force -Path $testPath
Set-Content $testPath $testContent


New-Item -ItemType File -Force -Path $docPath
Set-Content $docPath $docContent


Write-Host "Feature Created Successfully"
