export enum ChiefEngineerState {
 IDLE="IDLE",
 ANALYZING="ANALYZING",
 PLANNING="PLANNING",
 BUILDING="BUILDING",
 TESTING="TESTING",
 REPAIRING="REPAIRING",
 DEPLOYING="DEPLOYING",
 READY="READY",
 FAILED="FAILED"
}

