export enum MissionState {
    CREATED="CREATED",
    PLANNING="PLANNING",
    APPROVED="APPROVED",
    EXECUTING="EXECUTING",
    TESTING="TESTING",
    REPAIRING="REPAIRING",
    COMPLETED="COMPLETED",
    FAILED="FAILED"
}
